server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:memDb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
